### ISSUE TITLE
Console Errors during "Add New Card"

### ISSUE THREAD

**Issue by bdaley** [GreenhouseStudios/sourcery-web-app#212]
## Tell us about your device

Firefox on Desktop

### What steps will reproduce the bug?

Log in and attempt to add a new credit card

### How often does it reproduce? Is there a required condition?
N/A

### What is the expected behavior?

No errors

### What do you see instead?

![image](https://user-images.githubusercontent.com/382814/111524492-dcf39e80-8732-11eb-9e91-9beab7a494ee.png)

![image](https://user-images.githubusercontent.com/382814/111524474-d7965400-8732-11eb-84a2-b28080a5fb33.png)

**Comment by briankelleher** [comment]
This doesn't seem to be a CORS issue any longer, however I did experience a longer wait time to load on FF initially with some console **warnings**:

```
Feature Policy: Skipping unsupported feature name “payment”. v3:1:39765
Feature Policy: Skipping unsupported feature name “payment”. v3:1:39857
Feature Policy: Skipping unsupported feature name “payment”. v3:1:151601
Unrecognized create() parameter: base is not a recognized parameter. This may cause issues with your integration in the future. controller-dbfe97e19c4be520e3049e2bc30f8936.js:1:2663
Unrecognized create() parameter: invalid is not a recognized parameter. This may cause issues with your integration in the future.
```

@bdaley are these known console warnings or want me to investigate?  Doesn't seem to affect the ability to add a card, which is good.

Was able to add the Stripe test card as well with no issues on FF.

**Comment by bdaley** [comment]
It's probably (maybe?) be a stripe elements issue: [https://stripe.com/payments/elements](https://stripe.com/payments/elements)

I'm not sure we're even close to the latest version. Plus, it was only available as vanilla js (rather than as vue components) so there are probably issues with the installation/configuration. 

Probably not a huge priority at the moment, but we'll need to resolve it soon. It's up to you.

**Comment by briankelleher** [comment]
It does appear that Stripe v3 is the most recent stable version, so I think you are fine there.

So the initial message, Feature Policy issue - this is directly related to the Feature Policy header, which coincidentally is not supported in Firefox.  So these will be unavoidable warnings in Firefox.  [Read more here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/payment#browser_compatibility).

I think we will need to keep an eye on this, because it appears that the header name is actually still in spec and being renamed, however I could not find evidence in the app that we set this, so it must be stripe.

Submitting pull request to resolve the other two warnings - Stripe API to create card element changed slightly to group styles under a single object.

**Comment by bdaley** [comment]
OK - Guess we leave the feature policy stuff for now.

I _thought_ the `unrecognized create() parameter` might be related to the `create()` method in stripe elements.

They have a React component, but nothing for Vue yet. That means that you have to manually integrate their vanilla js version into Vue. I remember it being really wonky in the past. Like, if the DOM element wasn't loaded, `create()` would bug out or something. I could be wrong though.

We used a tutorial like this one to get it working: [https://www.digitalocean.com/community/tutorials/vuejs-stripe-elements-vue-integration.](https://www.digitalocean.com/community/tutorials/vuejs-stripe-elements-vue-integration.) Not sure if that helps.

**Comment by briankelleher** [comment]
No worries, I have a patch for create() that appears to work. Will submit tomorrow.
