### ISSUE TITLE
Institutional Landing Pages

### ISSUE THREAD

**Issue by bdaley** [GreenhouseStudios/sourcery-web-app#216]
Institutions should have a landing page URL that they can market and share to customers.

For example: https://sourceryapp.org/folger

...might take you to the request page for documents at the Folger.

**Comment by briankelleher** [comment]
If we have this data in Firebase, we could try and write a custom route that checks listing of institutions and resolves to a specific component/page.  It would be a route extension that would run after all other routes, but before 404.  Thinking of [extendRoutes](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#extendroutes).  I'm just not sure if it would work nicely with an async request to Firebase.

We could surely do it with a static set of data held in the repo, like a simple Institutions.js file that exports an object of institutions/routes.

Otherwise, we could set a prefix/subdirectory for these (ex. [https://sourceryapp.org/i/folger](https://sourceryapp.org/i/folger)).  If we did this, we could maintain a set of data within Firebase/in repo and use something like: [https://github.com/nuxt-community/redirect-module](https://github.com/nuxt-community/redirect-module) (scroll to async example).

In either solution:
- We would need to extend the organizations collection in Firestore to include a URL friendly slug (probably related to [this card](https://github.com/GreenhouseStudios/sourcery-web-app/projects/5#card-58741949))
- We would need to write a fetch service for organizations based URL friendly slug


A nuxt pages/* page could be worked on concurrently with this as either solution can point to it.

Let me know your thoughts.

**Comment by briankelleher** [comment]
I realize now there is also Repositories, and I'm not 100% sure which is the better one to source from.  This might also be related to https://github.com/GreenhouseStudios/sourcery-web-app/issues/226 where we can start hooking up valid institutions (organizations/repositories?)

**Comment by bdaley** [comment]
For now, it's set up in sort of a traditional, relational way. That is, there are keys/foreign keys that connect organizations with their repositories. So in #226, we would have "Boston College Libraries" as the organization, but there are two repositories that are linked to the overall organization. (This is due in large part to the recent pivot. We never had organizations in the DB before, so they couldn't easily be made into parent collections of the repositories.)

I think what we want is a landing page for each **organization**. At the very least, it might show the repositories/archives for that organization and allow you to place a request at a specific repository. Maybe even email them eventually? But let's think agile for now.

\<hr>

And for added context...

We have long-term plans to overhaul the data models, since Firebase introduced collection group queries: [https://firebase.googleblog.com/2019/06/understanding-collection-group-queries.html](https://firebase.googleblog.com/2019/06/understanding-collection-group-queries.html)

So eventually, we might have something like:

*   Organization Collection
    *   Repository Subcollection(?)
        *   Request Subcollection(?)

Rather than two separate collections with relational keys.
